GameOfLife\Domain\Event\GenerationEnded:
    exclusion_policy: ALL
    properties:
        colonyId:
            type: GameOfLife\Domain\Colony\ColonyId

        eventDate:
            type: DateTimeInterface

        generation:
            type: int
