GameOfLife\Domain\Event\CellBorn:
    exclusion_policy: ALL
    properties:
        colonyId:
            type: GameOfLife\Domain\Colony\ColonyId

        eventDate:
            type: DateTimeInterface

        index:
            type: int
