default:
    formatters:
        progress: true
    extensions:
        FriendsOfBehat\SymfonyExtension:
            bootstrap: ~
            kernel:
                class: 'GameOfLife\Infrastructure\Kernel'
                path: ~
                environment: ~
                debug: ~
        Behat\MinkExtension:
            sessions:
                symfony:
                    symfony: ~
    suites:
        default:
            paths:
                - '%paths.base%/../features'
            contexts:
                - 'Behat\MinkExtension\Context\MinkContext'
                - 'GameOfLife\Tests\Behat\FeatureContext'
