services:
    _defaults:
        autowire: true
        autoconfigure: true

    GameOfLife\Tests\Behat\:
        resource: '../tests/Behat/'
        exclude: '../tests/Behat/*Test.php'

    GameOfLife\Tests\Behat\ColonyHistory\Parser:
        public: true
