parameters:
    database_url: '%env(resolve:DATABASE_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    GameOfLife\:
        resource: '../src/'
        exclude:
            - '../src/Infrastructure/Kernel.php'

    GameOfLife\Infrastructure\Controller\:
        resource: '../src/Infrastructure/Controller/'
        tags:
            - 'controller.service_arguments'

    #                                                                                             #
    # Domain services                                                                             #
    #                                                                                             #

    GameOfLife\Domain\Colony\ColonyFactoryInterface:
        '@GameOfLife\Domain\Colony\ColonyFactory'

    GameOfLife\Domain\Colony\ColonyRepositoryInterface:
        '@GameOfLife\Infrastructure\Colony\SqliteColonyRepository'

    GameOfLife\Domain\Colony\EvolveCellInterface:
        '@GameOfLife\Domain\Colony\EvolveCell'

    GameOfLife\Domain\Time\ClockInterface:
        '@GameOfLife\Infrastructure\Time\UtcClock'

    #                                                                                             #
    # Infrastructure services                                                                     #
    #                                                                                             #

    GameOfLife\Infrastructure\Bus\ApplicationBusInterface:
        '@GameOfLife\Infrastructure\Bus\DispatcherBus'

    GameOfLife\Infrastructure\Bus\DispatcherBus:
        calls:
            -
                method: register
                arguments: ['@GameOfLife\Application\Command\Colony\CreateColony']
            -
                method: register
                arguments: ['@GameOfLife\Application\Command\Colony\EvolveColony']
            -
                method: register
                arguments: ['@GameOfLife\Application\Query\Colony\GetColony']

    GameOfLife\Infrastructure\Bus\LoggerBus:
        decorates: GameOfLife\Infrastructure\Bus\DispatcherBus
        decoration_priority: 1

    GameOfLife\Infrastructure\Bus\ExceptionFilterBus:
        decorates: GameOfLife\Infrastructure\Bus\DispatcherBus
        decoration_priority: 2

    GameOfLife\Infrastructure\Bus\ValidatorBus:
        decorates: GameOfLife\Infrastructure\Bus\DispatcherBus
        decoration_priority: 3

    GameOfLife\Infrastructure\Bus\CommandBusInterface:
        '@GameOfLife\Infrastructure\Bus\CommandBus'

    GameOfLife\Infrastructure\Bus\QueryBusInterface:
        '@GameOfLife\Infrastructure\Bus\QueryBus'

    GameOfLife\Infrastructure\Colony\GenerateCellStateInterface:
        '@GameOfLife\Infrastructure\Colony\GenerateRandomCellState'

    GameOfLife\Infrastructure\Database\ConnectionInterface:
        '@GameOfLife\Infrastructure\Database\PdoConnection'

    GameOfLife\Infrastructure\Database\PdoConnection:
        arguments:
            $databaseUrl: '%database_url%'

    GameOfLife\Infrastructure\Database\EventStoreInterface:
        '@GameOfLife\Infrastructure\Database\SqliteEventStore'

    GameOfLife\Infrastructure\Identifier\GenerateEntityIdSeedInterface:
        '@GameOfLife\Infrastructure\Identifier\GenerateUuid'

    GameOfLife\Infrastructure\Logger\LoggerInterface:
        '@GameOfLife\Infrastructure\Logger\PsrLoggerAdapter'

    GameOfLife\Infrastructure\Serializer\SerializerInterface:
        '@GameOfLife\Infrastructure\Serializer\JmsSerializerAdapter'

    GameOfLife\Infrastructure\Validator\ValidatorInterface:
        '@GameOfLife\Infrastructure\Validator\SymfonyValidatorAdapter'
