parameters:
    database_url: '%env(resolve:DATABASE_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    GameOfLife\:
        resource: '../src/'
        exclude:
            - '../src/Infrastructure/Kernel.php'

    GameOfLife\Infrastructure\Controller\:
        resource: '../src/Infrastructure/Controller/'
        tags:
            - 'controller.service_arguments'
