parameters:
    database_url: '%env(resolve:DATABASE_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    GameOfLife\:
        resource: '../src/'
        exclude:
            - '../src/Infrastructure/Kernel.php'

    GameOfLife\Infrastructure\Controller\:
        resource: '../src/Infrastructure/Controller/'
        tags:
            - 'controller.service_arguments'

    #                                                                                             #
    # Domain services                                                                             #
    #                                                                                             #

    GameOfLife\Domain\Colony\ColonyFactoryInterface:
        '@GameOfLife\Domain\Colony\ColonyFactory'

    GameOfLife\Domain\Colony\ColonyRepositoryInterface:
        '@GameOfLife\Mock\FakeColonyRepository'

    GameOfLife\Domain\Colony\EvolveCellInterface:
        '@GameOfLife\Domain\Colony\EvolveCell'

    GameOfLife\Domain\Time\ClockInterface:
        '@GameOfLife\Infrastructure\Time\UtcClock'

    #                                                                                             #
    # Infrastructure services                                                                     #
    #                                                                                             #

    GameOfLife\Infrastructure\Logger\LoggerInterface:
        '@GameOfLife\Infrastructure\Logger\PsrLoggerAdapter'

    GameOfLife\Infrastructure\Serializer\SerializerInterface:
        '@GameOfLife\Infrastructure\Serializer\JmsSerializerAdapter'
