services:
    _defaults:
        autowire: true
        autoconfigure: true

    GameOfLife\Tests\Behat\:
        resource: '../tests/Behat/'
        exclude: '../tests/Behat/*Test.php'

    GameOfLife\Domain\Colony\ColonyFactory:
        public: true

    GameOfLife\Infrastructure\Colony\SqliteColonyRepository:
        public: true

    GameOfLife\Tests\Behat\ColonyHistory\Parser:
        public: true
