Feature: Create a new colony

  In order to start the game of life
  As a user
  I need to be able to create a new colony

  Business rules:
    - The ID of a new colony is a UUID generated by the application
    - The width and height of a colony are strictly positive numbers
    - The repartition between dead and live cells is random


  Background:

    Given the next generated UUID will be "59494a9a-32cc-481e-a4f1-093a8dcef162"
    And the next generated colony will be:
    """
      [ ][*][*][ ]
      [*][ ][ ][*]
      [ ][*][*][ ]
    """


  Scenario: Successful colony creation

    When I go to "/colony"
    And I follow "new"
    And I fill in the following:
      | width  | 4 |
      | height | 3 |
    And I press "create"
    Then I should see the colony "59494a9a-32cc-481e-a4f1-093a8dcef162" at generation 0:
    """
      [ ][*][*][ ]
      [*][ ][ ][*]
      [ ][*][*][ ]
    """


  Scenario Outline: Form validation failure

    When I go to "/colony"
    And I follow "new"
    And I fill in the following:
      | width  | <width>  |
      | height | <height> |
    And I press "create"
    Then I should be on "/colony/new"
    And I should see "<error>"

    Examples:
      | width | height | error                                   |
      | 0     | 3      | The width should be a positive number.  |
      | 4     | 0      | The height should be a positive number. |
